# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.9.0
_src_path: gh:quickplates/meta
accountname: quickplates
description: NestJS service template 🐈
example: true
exampleaccountname: quickplates
exampledescription: NestJS service example 🐈
examplereponame: nest-example
reponame: nest
repourl: https://github.com/quickplates/nest
type: service
